spring:
  application:
    name: aiservice
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness-ai
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

eureka:
  client:
    service-url:
      # Point to the Eureka Server instance
      defaultZone: http://localhost:8761/eureka

